name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Add JitPack repository
      run: echo "maven { url 'https://jitpack.io' }" >> settings.gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ~/.gradle/wrapper/dists/gradle-*/**/gradle


    - name: Build with Gradle
      run: ./gradlew build
